### ISSUE TITLE
Cache is not invalidated when an entry changes

### ISSUE THREAD

**Issue by badnack** [jdurand/kaminari-cache#1]
Is there a way to force the cache invalidation? Every time I modify an entry in a table, this is not showed.

**Comment by jdurand** [comment]
@badnack, I haven't maintained or even used this gem in production. It was a naive approach to a non-problem.

If you're thinking about caching your resource pagination queries, I'm guessing you're starting a new project with performance in mind. That's the thinking I had when writing this gem.
It ended up getting in my way most of the time and I didn't gain more than 3ms improvement for the trouble. In this use case most of the time is lost in template rendering, so I'd suggest caching at the view layer instead.

Event worst, with this gem you lose ARs lazy loading mechanism; by caching at the template level, the DB queries won't fire unless the data is needed, so in a case of cache hit, your DB isn't hit anyway.

And yes, the cache sweeper doesn't seem to do its job for some reason...

I don't recommend using this gem, but if you do find a valid use case, I'll be happy to take pull requests.
