### ISSUE TITLE
Error: There is a circular dependency between kaminari-cache and kaminari-cache

### ISSUE THREAD

**Issue by abhi951990** [jdurand/kaminari-cache#2]
Hello,

I was implementing caching in my project, then I came across this gem. I added it to my gem file and ran Bundle Install, I got this error: 
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'kaminari-cache' and try again.

Then I tried, gem install kaminari-cache, I got this error: 
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between kaminari-cache and kaminari-cache

I am using following gems related to Kaminari:
gem 'kaminari', '~> 0.17.0'  # pagination
gem 'bootstrap-kaminari-views' 
gem 'grape-kaminari'

Thank you

**Comment by jdurand** [comment]
This is fixed, but for reasons outlined in https://github.com/jdurand/kaminari-cache/issues/1 I would not recommend you use this gem.
